server:
  port: ${PORT:8096}
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    usename: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-plataform: org.hibernate.dialect.H2Dialect
